// Demo data for analytics dashboard to showcase functionality
export const demoAnalyticsData = {
  timeRange: 30,
  metrics: {
    totalComplaints: 127,
    closedComplaints: 89,
    escalatedComplaints: 8,
    resolutionRate: 70.08,
    escalationRate: 6.30,
    avgResolutionTime: 24.3,
  },
  charts: {
    dailyTrends: [
      { date: '2024-01-01', received: 5, resolved: 3, escalated: 0 },
      { date: '2024-01-02', received: 8, resolved: 4, escalated: 1 },
      { date: '2024-01-03', received: 6, resolved: 5, escalated: 0 },
      { date: '2024-01-04', received: 12, resolved: 7, escalated: 2 },
      { date: '2024-01-05', received: 4, resolved: 8, escalated: 0 },
      { date: '2024-01-06', received: 7, resolved: 6, escalated: 1 },
      { date: '2024-01-07', received: 9, resolved: 5, escalated: 0 },
      { date: '2024-01-08', received: 11, resolved: 9, escalated: 1 },
      { date: '2024-01-09', received: 6, resolved: 7, escalated: 0 },
      { date: '2024-01-10', received: 8, resolved: 6, escalated: 1 },
      { date: '2024-01-11', received: 10, resolved: 8, escalated: 0 },
      { date: '2024-01-12', received: 5, resolved: 9, escalated: 0 },
      { date: '2024-01-13', received: 7, resolved: 4, escalated: 1 },
      { date: '2024-01-14', received: 9, resolved: 6, escalated: 0 },
      { date: '2024-01-15', received: 13, resolved: 8, escalated: 1 },
    ],
    statusDistribution: [
      { name: 'Open', value: 15, status: 'open' },
      { name: 'Assigned', value: 12, status: 'assigned' },
      { name: 'In Progress', value: 23, status: 'in_progress' },
      { name: 'Closed', value: 89, status: 'closed' },
      { name: 'Escalated', value: 8, status: 'escalated' },
    ],
    urgencyDistribution: [
      { name: 'Low', value: 45, urgency: 'low' },
      { name: 'Medium', value: 52, urgency: 'medium' },
      { name: 'High', value: 25, urgency: 'high' },
      { name: 'Critical', value: 5, urgency: 'critical' },
    ],
    categoryDistribution: [
      { name: 'Billing', value: 32 },
      { name: 'Technical Support', value: 28 },
      { name: 'Account Issues', value: 18 },
      { name: 'Product Defect', value: 15 },
      { name: 'Service Quality', value: 12 },
      { name: 'Delivery', value: 10 },
      { name: 'Refund Request', value: 8 },
      { name: 'Other', value: 4 },
    ],
    resolutionTimes: [
      { category: 'Billing', avgHours: 4.2, count: 32 },
      { category: 'Technical Support', avgHours: 18.5, count: 28 },
      { category: 'Account Issues', avgHours: 2.8, count: 18 },
      { category: 'Product Defect', avgHours: 36.7, count: 15 },
      { category: 'Service Quality', avgHours: 12.3, count: 12 },
      { category: 'Delivery', avgHours: 8.9, count: 10 },
      { category: 'Refund Request', avgHours: 1.5, count: 8 },
    ],
    recentAssignments: [
      { date: '2024-01-01', assignments: 3 },
      { date: '2024-01-02', assignments: 5 },
      { date: '2024-01-03', assignments: 2 },
      { date: '2024-01-04', assignments: 7 },
      { date: '2024-01-05', assignments: 4 },
      { date: '2024-01-06', assignments: 6 },
      { date: '2024-01-07', assignments: 3 },
      { date: '2024-01-08', assignments: 8 },
      { date: '2024-01-09', assignments: 4 },
      { date: '2024-01-10', assignments: 5 },
    ],
    categoryStatusCross: [
      { category: 'Billing', status: 'closed', count: 25 },
      { category: 'Billing', status: 'in_progress', count: 5 },
      { category: 'Billing', status: 'open', count: 2 },
      { category: 'Technical Support', status: 'closed', count: 18 },
      { category: 'Technical Support', status: 'in_progress', count: 8 },
      { category: 'Technical Support', status: 'escalated', count: 2 },
      { category: 'Account Issues', status: 'closed', count: 15 },
      { category: 'Account Issues', status: 'assigned', count: 3 },
      { category: 'Product Defect', status: 'closed', count: 10 },
      { category: 'Product Defect', status: 'in_progress', count: 3 },
      { category: 'Product Defect', status: 'escalated', count: 2 },
      { category: 'Service Quality', status: 'closed', count: 8 },
      { category: 'Service Quality', status: 'in_progress', count: 3 },
      { category: 'Service Quality', status: 'assigned', count: 1 },
      { category: 'Delivery', status: 'closed', count: 7 },
      { category: 'Delivery', status: 'in_progress', count: 2 },
      { category: 'Delivery', status: 'open', count: 1 },
      { category: 'Refund Request', status: 'closed', count: 6 },
      { category: 'Refund Request', status: 'in_progress', count: 2 },
    ],
    employeePerformance: [
      { employeeId: 1, name: 'Alice Johnson', totalAssigned: 25, resolved: 20, escalated: 1, resolutionRate: 80.0, avgResolutionHours: 6.5 },
      { employeeId: 2, name: 'Bob Smith', totalAssigned: 22, resolved: 18, escalated: 2, resolutionRate: 81.82, avgResolutionHours: 4.2 },
      { employeeId: 3, name: 'Carol Davis', totalAssigned: 20, resolved: 15, escalated: 1, resolutionRate: 75.0, avgResolutionHours: 8.8 },
      { employeeId: 4, name: 'David Wilson', totalAssigned: 18, resolved: 14, escalated: 0, resolutionRate: 77.78, avgResolutionHours: 3.3 },
      { employeeId: 5, name: 'Eva Martinez', totalAssigned: 15, resolved: 12, escalated: 1, resolutionRate: 80.0, avgResolutionHours: 12.1 },
      { employeeId: 6, name: 'Frank Thompson', totalAssigned: 12, resolved: 10, escalated: 0, resolutionRate: 83.33, avgResolutionHours: 5.7 },
      { employeeId: 7, name: 'Grace Lee', totalAssigned: 10, resolved: 8, escalated: 1, resolutionRate: 80.0, avgResolutionHours: 14.4 },
      { employeeId: 8, name: 'Henry Brown', totalAssigned: 8, resolved: 6, escalated: 0, resolutionRate: 75.0, avgResolutionHours: 7.9 },
    ],
    urgencyStatusCross: [
      { urgencyLevel: 'low', status: 'closed', count: 35 },
      { urgencyLevel: 'low', status: 'in_progress', count: 8 },
      { urgencyLevel: 'low', status: 'assigned', count: 2 },
      { urgencyLevel: 'medium', status: 'closed', count: 30 },
      { urgencyLevel: 'medium', status: 'in_progress', count: 15 },
      { urgencyLevel: 'medium', status: 'assigned', count: 5 },
      { urgencyLevel: 'medium', status: 'open', count: 2 },
      { urgencyLevel: 'high', status: 'closed', count: 18 },
      { urgencyLevel: 'high', status: 'in_progress', count: 5 },
      { urgencyLevel: 'high', status: 'escalated', count: 2 },
      { urgencyLevel: 'critical', status: 'closed', count: 2 },
      { urgencyLevel: 'critical', status: 'escalated', count: 3 },
    ],
  },
};

export const demoComplaints = [
  {
    id: 'demo-1',
    referenceNumber: 'CMP-2024-001',
    description: 'Unable to access my online banking account after recent update',
    additionalDetails: 'Error occurs when trying to log in with correct credentials',
    category: 'Technical Support',
    subCategory: 'Login Issues',
    urgencyLevel: 'high',
    status: 'in_progress',
    assignedTo: 1,
    createdAt: new Date('2024-01-15T10:30:00'),
    updatedAt: new Date('2024-01-15T14:20:00'),
    resolvedAt: null,
    customerId: 101,
    customerName: 'John Smith',
    customerEmail: 'john.smith@email.com',
    customerPhone: '+1-555-0123',
  },
  {
    id: 'demo-2',
    referenceNumber: 'CMP-2024-002',
    description: 'Billing discrepancy on monthly statement',
    additionalDetails: 'Charged for services not used during December',
    category: 'Billing',
    subCategory: 'Invoice Error',
    urgencyLevel: 'medium',
    status: 'assigned',
    assignedTo: 1,
    createdAt: new Date('2024-01-14T09:15:00'),
    updatedAt: new Date('2024-01-14T11:45:00'),
    resolvedAt: null,
    customerId: 102,
    customerName: 'Sarah Johnson',
    customerEmail: 'sarah.j@email.com',
    customerPhone: '+1-555-0456',
  },
  {
    id: 'demo-3',
    referenceNumber: 'CMP-2024-003',
    description: 'Product arrived damaged - screen cracked',
    additionalDetails: 'Package was intact but internal product was damaged',
    category: 'Product Defect',
    subCategory: 'Physical Damage',
    urgencyLevel: 'high',
    status: 'closed',
    assignedTo: 1,
    createdAt: new Date('2024-01-12T16:20:00'),
    updatedAt: new Date('2024-01-13T10:30:00'),
    resolvedAt: new Date('2024-01-13T10:30:00'),
    customerId: 103,
    customerName: 'Mike Wilson',
    customerEmail: 'mike.w@email.com',
    customerPhone: '+1-555-0789',
  },
  {
    id: 'demo-4',
    referenceNumber: 'CMP-2024-004',
    description: 'Request for refund on subscription service',
    additionalDetails: 'Service did not meet expectations, requesting full refund',
    category: 'Refund Request',
    subCategory: 'Service Dissatisfaction',
    urgencyLevel: 'low',
    status: 'open',
    assignedTo: 1,
    createdAt: new Date('2024-01-11T13:45:00'),
    updatedAt: null,
    resolvedAt: null,
    customerId: 104,
    customerName: 'Emily Davis',
    customerEmail: 'emily.d@email.com',
    customerPhone: '+1-555-0321',
  },
  {
    id: 'demo-5',
    referenceNumber: 'CMP-2024-005',
    description: 'Critical system outage affecting business operations',
    additionalDetails: 'Multiple users unable to access core functionality',
    category: 'Technical Support',
    subCategory: 'System Outage',
    urgencyLevel: 'critical',
    status: 'escalated',
    assignedTo: 1,
    createdAt: new Date('2024-01-10T08:00:00'),
    updatedAt: new Date('2024-01-10T09:15:00'),
    resolvedAt: null,
    customerId: 105,
    customerName: 'Robert Chen',
    customerEmail: 'robert.c@email.com',
    customerPhone: '+1-555-0654',
  },
]; 