CREATE TABLE "customer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customer_id_seq" INCREMENT BY 1 MINVALUE 1000 MAXVALUE 2147483647 START WITH 1000 CACHE 1),
	"name" varchar NOT NULL,
	"email" varchar NOT NULL,
	"phone" varchar NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
