CREATE SEQUENCE "complaint_reference_number_seq";

CREATE TABLE "complaint" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference_number" text default ('CMP' || lpad(nextval('complaint_reference_number_seq')::text, 3, '0')),
	"chat_id" uuid NOT NULL,
	"customer_id" integer,
	"preferred_contact_method" varchar,
	"preferred_contact_info" text,
	"preferred_contact_time" varchar,
	"category_id" integer,
	"sub_category_id" integer,
	"description" text,
	"incident_date" timestamp,
	"incident_time" timestamp,
	"transaction_reference" text,
	"transaction_amount" numeric(15, 2),
	"product_details" text,
	"device_details" text,
	"app_details" text,
	"browser_details" text,
	"attachment_urls" text,
	"branch_details" text,
	"branch_employee" text,
	"atm_location" text,
	"fraud_details" text,
	"fraud_type" varchar,
	"fraud_amount" numeric(15, 2),
	"desired_resolution" text,
	"sentiment" varchar,
	"urgency_level" varchar,
	"assistant_notes" text,
	"assigned_to" integer,
	"is_draft" boolean DEFAULT true NOT NULL,
	"status" varchar,
	"resolution_notes" text,
	"resolved_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "complaint_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complaint_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "complaint_comment" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"complaint_id" uuid NOT NULL,
	"employee_id" integer,
	"comment" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "complaint_sub_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complaint_sub_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"category_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "chat" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ADD COLUMN "specialization" varchar NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ADD COLUMN "branch" varchar NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ADD COLUMN "level" varchar NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ADD COLUMN "is_available" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ADD COLUMN "max_load" integer DEFAULT 10 NOT NULL;--> statement-breakpoint
ALTER TABLE "employee" ADD COLUMN "current_load" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "complaint" ADD CONSTRAINT "complaint_chat_id_chat_id_fk" FOREIGN KEY ("chat_id") REFERENCES "public"."chat"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaint" ADD CONSTRAINT "complaint_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaint" ADD CONSTRAINT "complaint_category_id_complaint_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."complaint_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaint" ADD CONSTRAINT "complaint_sub_category_id_complaint_sub_category_id_fk" FOREIGN KEY ("sub_category_id") REFERENCES "public"."complaint_sub_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaint" ADD CONSTRAINT "complaint_assigned_to_employee_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."employee"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaint_comment" ADD CONSTRAINT "complaint_comment_complaint_id_complaint_id_fk" FOREIGN KEY ("complaint_id") REFERENCES "public"."complaint"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaint_comment" ADD CONSTRAINT "complaint_comment_employee_id_employee_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employee"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaint_sub_category" ADD CONSTRAINT "complaint_sub_category_category_id_complaint_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."complaint_category"("id") ON DELETE no action ON UPDATE no action;